export default {
  vacancies: [
    {
      key: 'departmentHead',
      vacancyTitle: 'Руководитель Департамента',
      vacancySkills: {
        experience: true,
        management: true,
        networking: false,
        cableManagement: false,
        student: false,
        remoteWork: false,
        communicative: true,
        teamwork: true,
        studying: true,
        dedicated: true,
        stressResistance: true,
        adaptive: true,
      },
      vacancyScore: 6,
    },
    {
      key: 'sysAdmin',
      vacancyTitle: 'Системный Администратор',
      vacancySkills: {
        experience: true,
        management: false,
        networking: false,
        cableManagement: false,
        student: false,
        remoteWork: true,
        communicative: true,
        teamwork: false,
        studying: true,
        dedicated: true,
        stressResistance: true,
        adaptive: true,
      },
      vacancyScore: 5,
    },
    {
      key: 'seniorFront',
      vacancyTitle: 'Старший Front-end разработчик',
      vacancySkills: {
        experience: true,
        management: false,
        networking: false,
        cableManagement: false,
        student: false,
        remoteWork: true,
        communicative: true,
        teamwork: true,
        studying: true,
        dedicated: true,
        stressResistance: true,
        adaptive: true,
      },
      vacancyScore: 5,
    },
    {
      key: 'projectManager',
      vacancyTitle: 'Менеджер Проектов',
      vacancySkills: {
        experience: true,
        management: true,
        networking: false,
        cableManagement: false,
        student: false,
        remoteWork: true,
        communicative: true,
        teamwork: true,
        studying: true,
        dedicated: true,
        stressResistance: true,
        adaptive: true,
      },
      vacancyScore: 4,
    },
    {
      key: 'cableMan',
      vacancyTitle: 'Кабельщик',
      vacancySkills: {
        experience: true,
        management: false,
        networking: false,
        cableManagement: true,
        student: false,
        remoteWork: true,
        communicative: true,
        teamwork: true,
        studying: true,
        dedicated: true,
        stressResistance: true,
        adaptive: true,
      },
      vacancyScore: 3,
    },
    {
      key: 'juniorFront',
      vacancyTitle: 'Стажер Front-end разработки',
      vacancySkills: {
        experience: false,
        management: false,
        networking: false,
        cableManagement: false,
        student: true,
        remoteWork: true,
        communicative: true,
        teamwork: true,
        studying: true,
        dedicated: true,
        stressResistance: true,
        adaptive: true,
      },
      vacancyScore: 2,
    },
  ],
};
